# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x9c3A2c791f45a13befFC7205aFB7bFc844759831"
    chainName: artelatestnet
    connections:
      - token: ethereum|holesky|0x261A4cE71DAae74E4e5Fb1B104b94CD6d2Ed7D44
    decimals: 6
    name: USD Coin
    standard: EvmHypSynthetic
    symbol: USDC
  - addressOrDenom: "0x261A4cE71DAae74E4e5Fb1B104b94CD6d2Ed7D44"
    chainName: holesky
    collateralAddressOrDenom: "0x16b29f45d3fffb9a17c1f09e92a8e1446d34eabc"
    connections:
      - token: ethereum|artelatestnet|0x9c3A2c791f45a13befFC7205aFB7bFc844759831
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
