# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xa8695083430f70b0Fb1d8Bc2694c0DcE35545Cc9"
    chainName: artelatestnet
    connections:
      - token: ethereum|holesky|0x872Cc813cDDcD6b946f6219B3c1d1eCF02797D03
    decimals: 6
    name: USD Coin
    standard: EvmHypSynthetic
    symbol: USDC
  - addressOrDenom: "0x872Cc813cDDcD6b946f6219B3c1d1eCF02797D03"
    chainName: holesky
    collateralAddressOrDenom: "0x16b29f45d3fffb9a17c1f09e92a8e1446d34eabc"
    connections:
      - token: ethereum|artelatestnet|0xa8695083430f70b0Fb1d8Bc2694c0DcE35545Cc9
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
