# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x2a3Ee1d94640cb883083ef0E2F6c3BDc1f76b088"
    chainName: artelatestnet
    connections:
      - token: ethereum|holesky|0xC4470CAa90ac44e3849C4Dc604287e5A3c21F383
    decimals: 18
    name: Ether
    standard: EvmHypSynthetic
    symbol: ETH
  - addressOrDenom: "0xC4470CAa90ac44e3849C4Dc604287e5A3c21F383"
    chainName: holesky
    connections:
      - token: ethereum|artelatestnet|0x2a3Ee1d94640cb883083ef0E2F6c3BDc1f76b088
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
